// Generated by CoffeeScript 1.7.1
(function() {
  module.exports = function() {
    var argv, greet, mygreet, parseArgs;
    greet = require("../lib/");
    parseArgs = require("minimist");
    argv = parseArgs(process.argv.slice(2));
    mygreet = greet(process.argv[2], argv.drunk);
    console.log(mygreet);
  };

}).call(this);
